.\objects\dmadrv.o: ..\Drivers\emdrv\dmadrv\src\dmadrv.c
.\objects\dmadrv.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\objects\dmadrv.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stddef.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\em_device.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b200f256gm48.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Include\core_cm3.h
.\objects\dmadrv.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Include\core_cmInstr.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Include\cmsis_armcc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Include\core_cmFunc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\system_efm32jg1b.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_msc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_emu.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_rmu.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_cmu.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_crypto.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_gpio_p.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_gpio.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_prs_ch.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_prs.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_ldma_ch.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_ldma.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_gpcrc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_timer_cc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_timer.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_usart.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_leuart.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_letimer.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_cryotimer.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_pcnt.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_i2c.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_adc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_acmp.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_idac.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_rtcc_cc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_rtcc_ret.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_rtcc.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_wdog_pch.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_wdog.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_dma_descriptor.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_devinfo.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_romtable.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_prs_signals.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_dmareq.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_af_ports.h
.\objects\dmadrv.o: ..\Drivers\CMSIS\Device\SiliconLabs\EFM32JG1B\Include\efm32jg1b_af_pins.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_cmu.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_assert.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_bus.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_core.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_common.h
.\objects\dmadrv.o: ..\Drivers\emdrv\dmadrv\inc\dmadrv.h
.\objects\dmadrv.o: ..\Drivers\emdrv\common\inc\ecode.h
.\objects\dmadrv.o: ..\Drivers\emlib\inc\em_ldma.h
.\objects\dmadrv.o: ..\Drivers\emdrv\dmadrv\config\dmadrv_config.h
